version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd server-node
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - server-node/**/*
